/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as NossosProjetosRouteImport } from './routes/nossos-projetos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipeIndexRouteImport } from './routes/equipe.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjetoSlugRouteImport } from './routes/projeto.$slug'
import { Route as EventoSlugRouteImport } from './routes/evento.$slug'
import { Route as EquipeSlugRouteImport } from './routes/equipe.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEventsRouteImport } from './routes/admin/events'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const NossosProjetosRoute = NossosProjetosRouteImport.update({
  id: '/nossos-projetos',
  path: '/nossos-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipeRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjetoSlugRoute = ProjetoSlugRouteImport.update({
  id: '/projeto/$slug',
  path: '/projeto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoSlugRoute = EventoSlugRouteImport.update({
  id: '/evento/$slug',
  path: '/evento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipeRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/doar': typeof DoarRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/eventos': typeof EventosRoute
  '/nossos-projetos': typeof NossosProjetosRoute
  '/obrigado': typeof ObrigadoRoute
  '/sobre': typeof SobreRoute
  '/superadmin': typeof SuperadminRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/equipe/': typeof EquipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/nossos-projetos': typeof NossosProjetosRoute
  '/obrigado': typeof ObrigadoRoute
  '/sobre': typeof SobreRoute
  '/superadmin': typeof SuperadminRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/equipe': typeof EquipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/doar': typeof DoarRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/eventos': typeof EventosRoute
  '/nossos-projetos': typeof NossosProjetosRoute
  '/obrigado': typeof ObrigadoRoute
  '/sobre': typeof SobreRoute
  '/superadmin': typeof SuperadminRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/equipe/': typeof EquipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/doar'
    | '/equipe'
    | '/eventos'
    | '/nossos-projetos'
    | '/obrigado'
    | '/sobre'
    | '/superadmin'
    | '/admin/events'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/team'
    | '/admin/users'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/evento/$slug'
    | '/projeto/$slug'
    | '/admin/'
    | '/blog/'
    | '/equipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doar'
    | '/eventos'
    | '/nossos-projetos'
    | '/obrigado'
    | '/sobre'
    | '/superadmin'
    | '/admin/events'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/team'
    | '/admin/users'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/evento/$slug'
    | '/projeto/$slug'
    | '/admin'
    | '/blog'
    | '/equipe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/doar'
    | '/equipe'
    | '/eventos'
    | '/nossos-projetos'
    | '/obrigado'
    | '/sobre'
    | '/superadmin'
    | '/admin/events'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/team'
    | '/admin/users'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/evento/$slug'
    | '/projeto/$slug'
    | '/admin/'
    | '/blog/'
    | '/equipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  DoarRoute: typeof DoarRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  EventosRoute: typeof EventosRoute
  NossosProjetosRoute: typeof NossosProjetosRoute
  ObrigadoRoute: typeof ObrigadoRoute
  SobreRoute: typeof SobreRoute
  SuperadminRoute: typeof SuperadminRoute
  EventoSlugRoute: typeof EventoSlugRoute
  ProjetoSlugRoute: typeof ProjetoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossos-projetos': {
      id: '/nossos-projetos'
      path: '/nossos-projetos'
      fullPath: '/nossos-projetos'
      preLoaderRoute: typeof NossosProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projeto/$slug': {
      id: '/projeto/$slug'
      path: '/projeto/$slug'
      fullPath: '/projeto/$slug'
      preLoaderRoute: typeof ProjetoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$slug': {
      id: '/evento/$slug'
      path: '/evento/$slug'
      fullPath: '/evento/$slug'
      preLoaderRoute: typeof EventoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EquipeRouteChildren {
  EquipeSlugRoute: typeof EquipeSlugRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeSlugRoute: EquipeSlugRoute,
  EquipeIndexRoute: EquipeIndexRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  DoarRoute: DoarRoute,
  EquipeRoute: EquipeRouteWithChildren,
  EventosRoute: EventosRoute,
  NossosProjetosRoute: NossosProjetosRoute,
  ObrigadoRoute: ObrigadoRoute,
  SobreRoute: SobreRoute,
  SuperadminRoute: SuperadminRoute,
  EventoSlugRoute: EventoSlugRoute,
  ProjetoSlugRoute: ProjetoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
