// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nopfxwvfirucyshyvfxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcGZ4d3ZmaXJ1Y3lzaHl2ZnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxMjk5MzAsImV4cCI6MjA5MzcwNTkzMH0.EHmBRC4xAqRqem5ii30Hk3ikXXO2y6hyLHiNsTF3PnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});